### ISSUE TITLE
AdminApp-Signin: Som en behörig användare ska jag kunna logga in med användarnamn och lösenord

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#11]
- [x] AdminApp-Signin: Fält för infyllnad ev epost
- [x] AdminApp-Signin: Fält för ifyllnad av lösenord
- [x] AdminApp-Signin: Vid knapptryck Login: Validera format epost med regEx. 
- [x] AdminApp-Signin: Vid knapptryck Login: Validera format lösenord med regEx
- [x] AdminApp-Signin: Check mot User api
- [x] AdminApp-Signin: Om User hittas (status Ok): Redirect till Home
- [x] AdminApp-Signin: Om User ej hittas (status Bad request): felmeddelande "misslyckad inloggning"

**Definition of done:**

- [x] Att formuläret är skapat med önskade fält.
- [x] Korrekt validering med RegEx vid knapptryck.
- [x] Rätt statuskod visas efter kontakt med Api.

**Comment by DennisMikaj** [comment]
![Image](https://github.com/user-attachments/assets/b6235dd9-674d-4e94-ab73-95a1b05c18b8)

**Comment by DennisMikaj** [comment]
![Image](https://github.com/user-attachments/assets/5234759a-6099-454d-a977-bb32ffe4eea6)
